version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade -t './code/lib' -r requirements.txt
  build:
    commands:
      - aws cloudformation package --template-file numpy-sam.yaml --s3-bucket $S3_BUCKET --output-template-file packaged-template.yaml
  post_build:
    commands:
      - aws cloudformation deploy --template-file packaged-template.yaml  --stack-name "ServerlessNumpy" --capabilities CAPABILITY_IAM --region us-east-1
artifacts:
  type: zip
  files:
    - packaged-template.yaml